Name:           ros-kinetic-geometric-shapes
Version:        0.5.1
Release:        0%{?dist}
Summary:        ROS geometric_shapes package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/geometric_shapes
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp
Requires:       boost-devel
Requires:       console-bridge-devel
Requires:       eigen3-devel
Requires:       qhull-devel
Requires:       ros-kinetic-eigen-stl-containers
Requires:       ros-kinetic-octomap
Requires:       ros-kinetic-random-numbers
Requires:       ros-kinetic-resource-retriever
Requires:       ros-kinetic-shape-msgs
Requires:       ros-kinetic-visualization-msgs
BuildRequires:  assimp-devel
BuildRequires:  boost-devel
BuildRequires:  console-bridge-devel
BuildRequires:  eigen3-devel
BuildRequires:  pkgconfig
BuildRequires:  qhull-devel
BuildRequires:  ros-kinetic-catkin >= 0.5.68
BuildRequires:  ros-kinetic-eigen-stl-containers
BuildRequires:  ros-kinetic-octomap
BuildRequires:  ros-kinetic-random-numbers
BuildRequires:  ros-kinetic-resource-retriever
BuildRequires:  ros-kinetic-rosunit
BuildRequires:  ros-kinetic-shape-msgs
BuildRequires:  ros-kinetic-visualization-msgs

%description
This package contains generic definitions of geometric shapes and bodies.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Tue Aug 23 2016 Ioan Sucan <isucan@google.com> - 0.5.1-0
- Autogenerated by Bloom

* Sun Jul 31 2016 Ioan Sucan <isucan@google.com> - 0.5.0-0
- Autogenerated by Bloom

* Mon Apr 04 2016 Ioan Sucan <isucan@google.com> - 0.4.4-0
- Autogenerated by Bloom

