Name:           ros-melodic-geometric-shapes
Version:        0.5.4
Release:        0%{?dist}
Summary:        ROS geometric_shapes package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/geometric_shapes
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp
Requires:       boost-devel
Requires:       console-bridge-devel
Requires:       eigen3-devel
Requires:       qhull-devel
Requires:       ros-melodic-eigen-stl-containers
Requires:       ros-melodic-octomap
Requires:       ros-melodic-random-numbers
Requires:       ros-melodic-resource-retriever
Requires:       ros-melodic-shape-msgs
Requires:       ros-melodic-visualization-msgs
BuildRequires:  assimp-devel
BuildRequires:  boost-devel
BuildRequires:  console-bridge-devel
BuildRequires:  eigen3-devel
BuildRequires:  pkgconfig
BuildRequires:  qhull-devel
BuildRequires:  ros-melodic-catkin >= 0.5.68
BuildRequires:  ros-melodic-eigen-stl-containers
BuildRequires:  ros-melodic-octomap
BuildRequires:  ros-melodic-random-numbers
BuildRequires:  ros-melodic-resource-retriever
BuildRequires:  ros-melodic-rosunit
BuildRequires:  ros-melodic-shape-msgs
BuildRequires:  ros-melodic-visualization-msgs

%description
This package contains generic definitions of geometric shapes and bodies.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Apr 06 2018 Dave Coleman <dave@dav.ee> - 0.5.4-0
- Autogenerated by Bloom

