Name:           ros-hydro-geometric-shapes
Version:        0.3.9
Release:        0%{?dist}
Summary:        ROS geometric_shapes package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/geometric_shapes
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp
Requires:       boost-devel
Requires:       eigen3-devel
Requires:       qhull-devel
Requires:       ros-hydro-console-bridge
Requires:       ros-hydro-eigen-stl-containers
Requires:       ros-hydro-octomap
Requires:       ros-hydro-random-numbers
Requires:       ros-hydro-resource-retriever
Requires:       ros-hydro-shape-msgs
Requires:       ros-hydro-shape-tools
BuildRequires:  assimp-devel
BuildRequires:  boost-devel
BuildRequires:  eigen3-devel
BuildRequires:  pkgconfig
BuildRequires:  qhull-devel
BuildRequires:  ros-hydro-catkin >= 0.5.68
BuildRequires:  ros-hydro-cmake-modules
BuildRequires:  ros-hydro-console-bridge
BuildRequires:  ros-hydro-eigen-stl-containers
BuildRequires:  ros-hydro-octomap
BuildRequires:  ros-hydro-random-numbers
BuildRequires:  ros-hydro-resource-retriever
BuildRequires:  ros-hydro-shape-msgs
BuildRequires:  ros-hydro-shape-tools

%description
This package contains generic definitions of geometric shapes and bodies.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Apr 30 2015 Ioan Sucan <isucan@google.com> - 0.3.9-0
- Autogenerated by Bloom

